### PR TITLE
Resolve #672: implement TE Refinery potion recipe functions.

### LINKED ISSUE #672: Thermal Expansion compatibility improvement - Alchemical Retort augment
#### Issue Description:

Similar to issue #631, Thermal Expansion's Refinery has specializations that changes what recipes are available. This only allows the recipes registered under this augment to be done, and you need the augment to do these recipes. The one I'm looking at is the Alchemical Retort, with enhances liquid potions

I used these lines:
var healingPotionThree = <liquid:potion>.withTag({Potion: "cofhcore:healing3"});
mods.thermalexpansion.Refinery.removeRecipe(healingPotionThree);

What happens:

ERROR: No Refinery recipe exists for: net.minecraftforge.fluids.FluidStack@5db7526

What you expected to happen:

I expected this recipe:
mod.thermalexpansion.Refinery.addRecipe(<liquid:potion>.withTag({Potion: "cofhcore:healing4"}) * 150, null, <liquid:potion>.withTag({Potion: "cofhcore:healing3"}) * 200, 2500);
would be removed.

I guess ModTweaker will need to be updated to account for how the Alchemical Retort augment works.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/TGWu9btN

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/MA0AuuBB

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:.12.2
- Forge: 14.23.4.2747
- Crafttweaker: CraftTweaker2-1.12-4.1.9
- ModTweaker: 4.0.13
- MTLib: 3.0.5

#### Your most recent log file where the issue was present: 

[crafttweaker.log](https://github.com/jaredlll08/ModTweaker/files/2294505/crafttweaker.log)

### PR DESCRIPTION
**Pull request by noobanidus**
I believe this fleshes out completely the implementation of the Fractioning Still/Refinery. Script used to test the new functions addRecipePotion and removeRecipePotion: https://pastebin.com/eFfHLU2z

### CODE REVIEW

File: src/main/java/com/blamejared/compat/thermalexpansion/Refinery.java [hunk 1]
```diff
@@ -54,23 +64,56 @@ protected String getRecipeInfo() {
             return LogHelper.getStackDescription(output);
         }
     }
-    
+
+    private static class AddPotion extends BaseAction {
+
+        private FluidStack output, input;
```
Comment (kindlich) [inline src/main/java/com/blamejared/compat/thermalexpansion/Refinery.java:70]: If you never change them, make them final ^^

Comment (noobanidus) [reply src/main/java/com/blamejared/compat/thermalexpansion/Refinery.java:70]: Again, the convention of all of the other thermalexpansion handlers is that they aren't final. I don't feel like it's my place to begin changing that.

**Comment by duely** [comment]
InductionSmelter recipe removal is sometimes weird when the recipe uses multiple of an item. According to King Lemming on the CoFH discord, the correct way to deal with this is to swap the order of items when calling removeRecipe. 

Otherwise, no error is raised but the recipe is not removed.
